name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@ubuntu-22-test"
    with:
      runs_on: "ubuntu-24.04"
    secrets: "inherit"

  Acceptance:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@ubuntu-22-test"
    with:
      flags: '--provision-prefer provision_service'
    secrets: "inherit"
